version: 2
jobs:
  build:
    working_directory: ~/portfolio-angular
    docker:
      - image: circleci/node:10.15.1

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: angular-build
          command: yarn ng build --prod

      - store_artifacts:
          path: tslint.xml
          prefix: lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - "	57:0d:62:c6:41:2b:93:77:be:c3:0f:2b:ee:43:f0:19"

      - run:
          name: Deploy Over SSH
          command: |
            scp -o StrictHostKeyChecking=no -r ./dist/portfolio-angular/* jama2864@fast.o2switch.net://home/jama2864/toto/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
